
# #local
GET http://localhost:8002/hello
Accept: application/json

#kong

GET http://localhost:8001/services
# Accept: application/json



GET http://localhost:8000/hello
Accept: application/json


GET http://localhost:8000/google
Accept: application/json